import React, { useState } from 'react';
import { User, UserRole } from '../types';
import { store, saveSupabaseConfig, getSupabaseConfig } from '../services/store';

interface AuthFormProps {
  onLogin: (user: User) => void;
}

const SQL_SETUP_CODE = `-- Run this in your Supabase SQL Editor

-- 1. Create Profiles Table
create table if not exists public.profiles (
  id uuid references auth.users on delete cascade primary key,
  email text,
  role text default 'USER',
  balance float default 100,
  "isBanned" boolean default false,
  wins int default 0,
  losses int default 0
);

-- 2. Create Transactions Table
create table if not exists public.transactions (
  id uuid default gen_random_uuid() primary key,
  "userId" uuid references public.profiles(id),
  type text,
  amount float,
  network text,
  address text,
  status text,
  timestamp bigint
);

-- 3. Create Settings Table
create table if not exists public.admin_settings (
  id int generated by default as identity primary key,
  "walletTrc20" text,
  "walletErc20" text,
  "walletBep20" text,
  "minDeposit" float,
  "minWithdraw" float,
  "minWager" float
);

-- 4. Insert Default Settings
insert into public.admin_settings 
("walletTrc20", "walletErc20", "walletBep20", "minDeposit", "minWithdraw", "minWager")
select 'T9yD14Nj9j7xAB4dbGeiX9h8zzCyrXYZ', '0x71C7656EC7ab88b098defB751B7401B5f6d8976F', '0x71C7656EC7ab88b098defB751B7401B5f6d8976F', 5, 5, 0.1
where not exists (select 1 from public.admin_settings);

-- 5. Disable RLS for Demo (Or configure policies as needed)
alter table public.profiles disable row level security;
alter table public.transactions disable row level security;
alter table public.admin_settings disable row level security;
`;

export const AuthForm: React.FC<AuthFormProps> = ({ onLogin }) => {
  const [isLogin, setIsLogin] = useState(true);
  const [email, setEmail] = useState('');
  const [password, setPassword] = useState('');
  const [isAdminMode, setIsAdminMode] = useState(false);
  const [loading, setLoading] = useState(false);
  
  const [showSettings, setShowSettings] = useState(false);
  const [settingsTab, setSettingsTab] = useState<'config' | 'sql'>('config');
  const sbConfig = getSupabaseConfig();
  const [sbUrl, setSbUrl] = useState(sbConfig.url);
  const [sbKey, setSbKey] = useState(sbConfig.key);

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    setLoading(true);

    let submitEmail = email.trim();
    if (!submitEmail.includes('@')) {
        submitEmail = `${submitEmail}@gmchess.com`;
    }

    try {
        if (isLogin) {
            const user = await store.login(submitEmail, password);
            if (user) {
                onLogin(user);
            } else {
                alert("Login failed. Please check your credentials.");
            }
        } else {
            // Sign Up Flow
            const user = await store.createUser(submitEmail, password, isAdminMode ? UserRole.ADMIN : UserRole.USER);
            if (user) {
                // AUTO-LOGIN: Directly log the user in after creation
                // Note: This requires "Confirm Email" to be disabled in Supabase project settings
                onLogin(user);
            }
        }
    } catch (e: any) {
        console.error(e);
        alert("Authentication Error: " + (e.message || "Unknown error"));
    } finally {
        setLoading(false);
    }
  };

  const handleAdminFill = () => {
    setEmail('admin@gmchess.com');
    setPassword('123456');
    setIsLogin(true); 
  };

  const handleSaveConfig = () => {
      saveSupabaseConfig(sbUrl, sbKey);
  };

  if (showSettings) {
      return (
        <div className="min-h-screen bg-dark-950 flex items-center justify-center p-4">
             <div className="bg-dark-900 border border-slate-800 p-8 rounded-2xl w-full max-w-lg shadow-2xl relative">
                <button onClick={() => setShowSettings(false)} className="absolute top-4 right-4 text-slate-500 hover:text-white">✕</button>
                <h2 className="text-xl font-bold mb-6">Supabase Setup</h2>
                
                <div className="flex gap-4 border-b border-slate-700 mb-6">
                    <button 
                        onClick={() => setSettingsTab('config')}
                        className={`pb-2 text-sm font-bold ${settingsTab === 'config' ? 'text-brand-400 border-b-2 border-brand-400' : 'text-slate-500'}`}
                    >
                        Credentials
                    </button>
                    <button 
                        onClick={() => setSettingsTab('sql')}
                        className={`pb-2 text-sm font-bold ${settingsTab === 'sql' ? 'text-brand-400 border-b-2 border-brand-400' : 'text-slate-500'}`}
                    >
                        Database SQL
                    </button>
                </div>

                {settingsTab === 'config' ? (
                    <div className="space-y-4 animate-in fade-in">
                        <p className="text-xs text-slate-400 mb-2">Connect your Supabase project to enable persistent user data.</p>
                        <div>
                            <label className="text-slate-500 text-xs font-bold">Supabase URL</label>
                            <input value={sbUrl} onChange={e => setSbUrl(e.target.value)} className="w-full bg-dark-950 border border-slate-700 rounded p-2 text-white font-mono text-sm" placeholder="https://xyz.supabase.co" />
                        </div>
                        <div>
                            <label className="text-slate-500 text-xs font-bold">Supabase Anon Key</label>
                            <input value={sbKey} onChange={e => setSbKey(e.target.value)} className="w-full bg-dark-950 border border-slate-700 rounded p-2 text-white font-mono text-sm" placeholder="eyJh..." />
                        </div>
                        <button onClick={handleSaveConfig} className="w-full bg-brand-600 hover:bg-brand-500 text-white py-2 rounded font-bold mt-2">Save & Connect</button>
                    </div>
                ) : (
                    <div className="space-y-4 animate-in fade-in">
                        <p className="text-xs text-slate-400">Copy and run this code in the <a href="https://supabase.com/dashboard/project/_/sql/new" target="_blank" className="text-brand-400 underline">Supabase SQL Editor</a> to create the required tables.</p>
                        <div className="relative">
                            <pre className="bg-dark-950 p-4 rounded-lg text-[10px] font-mono text-slate-300 h-64 overflow-y-auto border border-slate-800">
                                {SQL_SETUP_CODE}
                            </pre>
                            <button 
                                onClick={() => navigator.clipboard.writeText(SQL_SETUP_CODE).then(() => alert("SQL Copied!"))}
                                className="absolute top-2 right-2 px-2 py-1 bg-brand-900 text-brand-400 text-xs rounded hover:bg-brand-800"
                            >
                                Copy SQL
                            </button>
                        </div>
                    </div>
                )}
             </div>
        </div>
      );
  }

  return (
    <div className="min-h-screen bg-dark-950 flex items-center justify-center p-4">
      <div className="bg-dark-900 border border-slate-800 p-8 rounded-2xl w-full max-w-md shadow-2xl relative">
        <button onClick={() => setShowSettings(true)} className="absolute top-4 right-4 text-slate-600 hover:text-white">⚙️</button>
        <h1 className="text-3xl font-black text-brand-500 mb-2 text-center">GM Chess</h1>
        <p className="text-slate-400 text-center mb-8">
          {isLogin ? 'Sign in to continue' : 'Create your challenger account'}
        </p>

        <form onSubmit={handleSubmit} className="space-y-4">
          <div>
            <label className="text-slate-500 text-xs font-bold uppercase tracking-wider">Username / Email</label>
            <input 
              required
              type="text" 
              value={email}
              onChange={e => setEmail(e.target.value)}
              className="w-full bg-dark-950 border border-slate-700 rounded-lg p-3 text-white mt-1 focus:border-brand-500 outline-none"
              placeholder="Enter email or 'admin'"
            />
          </div>
          <div>
            <label className="text-slate-500 text-xs font-bold uppercase tracking-wider">Password</label>
            <input 
              required
              type="password" 
              value={password}
              onChange={e => setPassword(e.target.value)}
              className="w-full bg-dark-950 border border-slate-700 rounded-lg p-3 text-white mt-1 focus:border-brand-500 outline-none"
              placeholder="••••••••"
            />
          </div>
          
          {!isLogin && (
            <div className="flex items-center gap-2">
               <input 
                 type="checkbox" 
                 checked={isAdminMode} 
                 onChange={e => setIsAdminMode(e.target.checked)} 
                 id="admin-check"
               />
               <label htmlFor="admin-check" className="text-slate-400 text-sm">Create as Admin (Demo)</label>
            </div>
          )}

          <button 
            type="submit"
            disabled={loading}
            className="w-full py-3 bg-brand-600 hover:bg-brand-500 text-white font-bold rounded-lg shadow-lg shadow-brand-900/50 mt-4 transition-transform active:scale-95 disabled:opacity-50"
          >
            {loading ? 'Processing...' : (isLogin ? 'Enter Arena' : 'Create Account')}
          </button>
        </form>

        <div className="mt-8 pt-6 border-t border-slate-800 text-center space-y-4">
            <p className="text-slate-500 text-sm">
                {isLogin ? "Don't have an account? " : "Already have an account? "}
                <button 
                    onClick={() => setIsLogin(!isLogin)}
                    className="text-brand-400 hover:underline font-bold"
                >
                    {isLogin ? 'Sign Up' : 'Log In'}
                </button>
            </p>

            <button 
                onClick={handleAdminFill}
                className="text-xs text-slate-600 hover:text-brand-500 transition-colors flex items-center justify-center gap-1 mx-auto"
            >
                <span>⚡</span> Admin Panel Access
            </button>
            
            <p className="text-[10px] text-slate-700">
               Note: 'admin' will be treated as 'admin@gmchess.com'
            </p>
        </div>
      </div>
    </div>
  );
};